CC := mcs
CFLAGS := -r:System.Windows.Forms.dll -r:System.Drawing.dll -r:System.Data.dll

SRC := StudentEntryForm.cs Program.cs
TARGET := FirstPractice.exe

$(TARGET):
	$(CC) $(CFLAGS) $(SRC) -out:$@
